- name: Deploy ETL Stack
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create project directory
      file:
        path: /opt/etl-pipeline
        state: directory

    - name: Copy docker-compose file
      copy:
        src: docker-compose.yml
        dest: /opt/etl-pipeline/docker-compose.yml

    - name: Start containers
      command: docker-compose up -d
      args:
        chdir: /opt/etl-pipeline
